### ISSUE TITLE
Slow download button not being automatically clicked

### ISSUE THREAD

**Issue by octhunder89** [parsiad/wabbajack-autodownload#1]
Hei man, 
I did everything as in description and its not working. When it gets to first screen to click the slow download macro its not working. I tried both version 0.1.0 and 0.1.1

**Comment by agentallandev** [comment]
I wonder if Wabbajack or Nexus updated and patched/broke the system.  I'll look into trying to fix it

**Comment by agentallandev** [comment]
I found the issue.  It cannot find the button on the screen

**Comment by octhunder89** [comment]
Any solution ?

**Comment by parsiad** [comment]
The button click is done by image matching, and as far as I know, the image matching is not fuzzy. So if the image changes at all from what is expected (either because Nexus changed the button or because your browser renders it differently than mine) it will fail.

**A quick hack would be to clone the repo replace the images in the [images folder](https://github.com/parsiad/wabbajack-autodownload/tree/main/images) with screenshots of the corresponding buttons obtained from your computer.** This should be fairly easy to do.

I unfortunately don't have the time to make this more robust, but am happy to review and merge PRs. AFAIK, Pulover's does not have a fuzzy image matching feature, unfortunately.

**Comment by octhunder89** [comment]
So, if anyone wants to use, just take a screenshot and cut that button and replace the original one. I belive it wasnt working because of different monitor render (resolution) also, i could only manage to make it work on primary monitor.

**Comment by yohancarvalho** [comment]
![slow d 2](https://user-images.githubusercontent.com/95389461/144336086-54e42c8b-a772-44b3-9aa5-da1b9eef7afc.png)
You can use this image

**Comment by parsiad** [comment]
Thanks @yohancarvalho. I'm happy to merge this if someone else can independently confirm it works (@octhunder89, @allanep9 ?)

**Comment by uberspringer** [comment]
I managed to get it to work. Had to take my own screenshot of the button though. Still thanks to everyone and especially @parsiad for making this. Another paywall circumvented!

**Comment by parsiad** [comment]
I have added a link to this thread to the README and am closing it.

If anybody wants to discuss or work on a robust fix to this problem, please create a new issue or submit a PR.
